<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.jacksonheylion</groupId>
    <artifactId>java-pmd7-compatibility</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>java17</module>
        <module>java21</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>21</maven.compiler.release>
        <maven.compiler.plugin.version>3.15.0</maven.compiler.plugin.version>
        <maven.pmd.plugin.version>3.28.0</maven.pmd.plugin.version>
        <pmd.version>7.26.0</pmd.version>
        <p3c.ruleset>${maven.multiModuleProjectDirectory}/../../config/pmd/p3c.xml</p3c.ruleset>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
                <version>${maven.pmd.plugin.version}</version>
                <configuration>
                    <targetJdk>${maven.compiler.release}</targetJdk>
                    <inputEncoding>${project.build.sourceEncoding}</inputEncoding>
                    <printFailingErrors>true</printFailingErrors>
                    <verbose>true</verbose>
                    <failOnViolation>true</failOnViolation>
                    <failurePriority>5</failurePriority>
                    <skipPmdError>false</skipPmdError>
                    <typeResolution>true</typeResolution>
                    <rulesets>
                        <ruleset>${p3c.ruleset}</ruleset>
                    </rulesets>
                </configuration>
                <executions>
                    <execution>
                        <id>verify-modern-java-parser</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>net.sourceforge.pmd</groupId>
                        <artifactId>pmd-core</artifactId>
                        <version>${pmd.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>net.sourceforge.pmd</groupId>
                        <artifactId>pmd-java</artifactId>
                        <version>${pmd.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>net.sourceforge.pmd</groupId>
                        <artifactId>pmd-javascript</artifactId>
                        <version>${pmd.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>net.sourceforge.pmd</groupId>
                        <artifactId>pmd-jsp</artifactId>
                        <version>${pmd.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>
